### ISSUE TITLE
Subf2m.co

### ISSUE THREAD

**Issue by Fhd-pro** [josdion/subbuzz#5]
Hi,

First thank you for this great plugin and I believe you should post it on the Emby fourm as I find by accident and very gald about that.

Anyhow, the provider Sub2fm has stopped working and nothing to tell since it's also stopped working on Bazarr and other plugins.

Do you plan for workaround or at least mark it as invalid porvider as it's causing emby to be stock on searching for subtitles without ever having any results.

**Comment by josdion** [comment]
Hi @Fhd-pro,
The subf2m stopped working, because they implemented java script challenge. I fix this issue in 1.0.5.0 by using node.js to calculate this challenge and set the cookie, but you need to install node. 

There is one additional issue with this provider - sometimes connection is blocked during SSL/TLS authentication phase and you can see if this is an issue when the following exception is in the log

`
subbuzz.Providers.Subf2m: ParseSubtitlesList Timeout error: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 20 seconds elapsing
`

Currently when that is happen in emby, the provider can be blocked for hours. The main issue with emby is that it still use .NET standard 2.0 so I don't have a workaround for this yet. The provider is working far better in jellyfin as it can set separate timeout for connection phase. I'll think for some better solution for this issue in the next version.

**Comment by Fhd-pro** [comment]
Thank you for your response that was really informative.
